// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-api.proto

package com.yamalc.ytmp.userapi.grpc;

public final class AuthenticateService {
  private AuthenticateService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yamalc_ytmp_userapi_AuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yamalc_ytmp_userapi_AuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yamalc_ytmp_userapi_AuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yamalc_ytmp_userapi_AuthenticateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016user-api.proto\022\027com.yamalc.ytmp.userap" +
      "i\"3\n\023AuthenticateRequest\022\n\n\002id\030\001 \001(\t\022\020\n\010" +
      "password\030\002 \001(\t\"2\n\024AuthenticateResponse\022\032" +
      "\n\022authenticateResult\030\003 \001(\0102u\n\004User\022m\n\014Au" +
      "thenticate\022,.com.yamalc.ytmp.userapi.Aut" +
      "henticateRequest\032-.com.yamalc.ytmp.usera" +
      "pi.AuthenticateResponse\"\000B;\n\034com.yamalc." +
      "ytmp.userapi.grpcB\023AuthenticateServiceP\001" +
      "\242\002\003SPTb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yamalc_ytmp_userapi_AuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yamalc_ytmp_userapi_AuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yamalc_ytmp_userapi_AuthenticateRequest_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_com_yamalc_ytmp_userapi_AuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yamalc_ytmp_userapi_AuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yamalc_ytmp_userapi_AuthenticateResponse_descriptor,
        new java.lang.String[] { "AuthenticateResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
