// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-api.proto

package com.yamalc.ytmp.userapi.grpc;

public interface AuthenticateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yamalc.ytmp.userapi.AuthenticateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool authenticateResult = 3;</code>
   */
  boolean getAuthenticateResult();
}
