// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-api.proto

package com.yamalc.ytmp.userapi.grpc;

public interface AuthenticateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yamalc.ytmp.userapi.AuthenticateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
